services:
  prometheus:
    restart: always
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    command:
      - '--storage.tsdb.retention.time=7d'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./docker/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./docker/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    depends_on:
      - prometheus

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo-config.yml" ]
    volumes:
      - ./docker/tempo/tempo-config.yaml:/etc/tempo-config.yml
      - tempo-data:/tmp/tempo

  grafana:
    restart: always
    image: grafana/grafana:10.3.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    ports:
      - "3001:3000"
    volumes:
      - ./docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus

  mariadb:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: animaldb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "10006:3306"
    volumes:
      - ./docker/mariadb/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - mariadb-data:/var/lib/mysql

  official-auto-otel-animal-app:
    restart: always
    build:
      context: ./official-auto-otel-animal-app
      dockerfile: Dockerfile
    container_name: official-auto-otel-animal-app
    env_file:
      - ./docker/otel-service-config.env
    environment:
      - OTEL_SERVICE_NAME=official-auto-otel-animal-app
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/animaldb
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - mariadb
    ports:
      - "8081:8080"

  aspect-based-otel-animal-app:
    restart: always
    build:
      context: ./aspect-based-otel-animal-app
      dockerfile: Dockerfile
    container_name: aspect-based-otel-animal-app
    env_file:
      - ./docker/otel-service-config.env
    environment:
      - OTEL_SERVICE_NAME=aspect-based-otel-animal-app
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/animaldb
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - mariadb
    ports:
      - "8082:8080"

  extension-based-otel-animal-app:
    restart: always
    build:
      context: ./extension-based-otel-animal-app
      dockerfile: Dockerfile
    container_name: extension-based-otel-animal-app
    env_file:
      - ./docker/otel-service-config.env
    environment:
      - OTEL_SERVICE_NAME=extension-based-otel-animal-app
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/animaldb
    deploy:
      resources:
        limits:
          memory: 1024M
    depends_on:
      - mariadb
    ports:
      - "8083:8080"

volumes:
  prometheus-data:
  tempo-data:
  mariadb-data:
