apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    isDefault: true
    url: http://tempo:3200
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090